---
AWSTemplateFormatVersion: '2010-09-09'
Description: Custom CFN Certificate Provider with DNS validation support
Parameters:
  ResourceBucketName:
    Type: String
    Default: ''
  CFNCustomProviderZipFileName:
    Type: String
    Default: 'cfn-certificate-provider-0.2.4.zip'
  UPCustomProviderZipFileName:
    Type: String
    Default: 'cfn-cognito-user-pools.zip'
  DomainName:
    Type: String
Resources:
  # First set of resources sets up the certificate provider
  LambdaPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaRole
    Properties:
      PolicyName: CFNCertificateDomainResourceRecordProvider
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - acm:RequestCertificate
              - acm:DescribeCertificate
              - acm:UpdateCertificateOptions
              - acm:DeleteCertificate
            Resource:
            - '*'
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource:
            - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:binxio-cfn-certificate-provider'
          - Effect: Allow
            Action:
              - logs:*
            Resource: arn:aws:logs:*:*:*
      Roles:
        - !Ref 'LambdaRole'
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  CFNCustomProvider:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaRole
    Properties:
      Description: CFN Certificate Domain Resource Record Provider
      Code:
        S3Bucket: !Ref ResourceBucketName
        S3Key: !Ref 'CFNCustomProviderZipFileName'
      FunctionName: binxio-cfn-certificate-provider
      Handler: provider.handler
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: python3.6
      Timeout: 300
